Make orb identity refresh resilient
Amp-Thread-ID: https://ampcode.com/threads/T-019febee-2ab7-73a9-b5f7-079c81a06b88

diff --git a/.amp/services.yaml b/.amp/services.yaml
--- a/.amp/services.yaml
+++ b/.amp/services.yaml
@@ -1,10 +1,14 @@
 services:
   aws-identity:
     command: |
-      set -eu
+      set -u
       while true; do
-        ./scripts/refresh-amp-aws-token
-        sleep 2700
+        if ./scripts/refresh-amp-aws-token; then
+          sleep 2700
+        else
+          echo "Amp AWS identity refresh failed; retrying in 30 seconds" >&2
+          sleep 30
+        fi
       done
 
   targeter-ui:
